GET http://localhost:3000/places?text=av prudente de morais, barro vermelho, 2525

###

GET http://localhost:3000/places?text=av amazonas, belo horizonte, 1000

###

@originId= ChIJPY8UdwIAswcRHN4yDwz_PfU

@destinationId= ChIJPUqddeKZpgARusD9CDpIBDQ

###

GET http://localhost:3000/directions?originId={{ originId }}&destinationId={{ destinationId }}

###

POST http://localhost:3000/routes
Content-Type: application/json

{
  "name": "rota 3",
  "source_id": "{{ originId }}",
  "destination_id": "{{ destinationId }}"
}

### 

GET http://localhost:3000/routes

###

GET http://localhost:3000/routes/67670f498b214db3c213940a